server:
  port: 0
  servlet:
    encoding:
      charset: UTF-8
      force: true
    session:
      timeout: 43200m
      cookie:
        max-age: 43200m
        name: SID
        http-only: true # js 조회 안됨
#        secure: true # https

eureka:
  instance:
    instance-id: smartpass-microservice-instance
    appname: smartpass-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: smartpass-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: local
  cache:
    redis
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:test-db
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create


module:
  jwt:
    secret-key: secretKey


feign-client:
  auth:
    url: http://localhost:8080/auth