server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

#eureka:
#  instance:
#    instance-id: gateway-microservice-instance
#    appname: gateway-service
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8686/eureka

spring:
  profiles:
    active: local
  cache:
    redis
  redis:
    host: localhost
    port: 6379
module:
  jwt:
    secret-key: secretKey

feign-client:
  auth:
    url: localhost:8080/auth