server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      force: true
    session:
      timeout: 43200m
      cookie:
        max-age: 43200m
        name: SID
        http-only: true # js 조회 안됨
        secure: true # https
#eureka:
#  instance:
#    instance-id: gateway-microservice-instance
#    appname: gateway-service
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8686/eureka

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  cache:
    redis
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      default-filters:
        - name: AuthorizationFilter
          args:
            baseMessage: Spring Cloud Gateway AuthorizationFilter
            preLogger: true
            postLogger: true
      routes:
        - id: smartpass-service
          uri: http://localhost:8180/
          predicates:
            - Path=/admin/**

module:
  jwt:
    secret-key: secretKey

feign-client:
  auth:
    url: localhost:8080/auth